import "@/assets/styles/globals.css"
import Header from "@/components/Header"
import Footer from "@/components/Footer"
import Navigation from "@/components/Navigation"

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Header />
				<div className="flex flex-row">
					<Navigation />
					<main className="container mx-auto max-w-[1440px] px-8 py-4">
						{children}
					</main>
				</div>
				<Footer />
			</body>
		</html>
	)
}
