import "@/assets/styles/globals.css"
import Header from "@/components/Header"
import Footer from "@/components/Footer"
import Navigation from "@/components/Navigation"

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<div className="">
					<Header />
					<Navigation />
					<main className="mt-16 ml-42">{children}</main>
					<Footer />
				</div>
			</body>
		</html>
	)
}
