import "@/assets/styles/globals.css"
import Footer from "@/components/Footer"
import Navigation from "@/components/Navigation"

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="bg-gray-50 text-gray-900">
				<div className="min-h-screen flex flex-col">
					<Navigation />
					<main className="flex-grow max-w-6xl mx-auto w-full px-4 py-8">
						{children}
					</main>
					<Footer />
				</div>
			</body>{" "}
		</html>
	)
}
